#!/bin/bash

name=actmp
if [ $# -ge 1 ]; then
    name=$1
fi

# prepare dir
path=$(pwd)/$name
mkdir -p $path
cd $path || {
    echo "cd $path"
    exit 1
}

# cpp file
cat << 'EOF' > main.cpp
#include <bits/stdc++.h>

int main()
{
    int n;
    std::cin >> n;
    std::vector<int> v(n);
    for (int i = 0; i < n; i++) { std::cin >> v[i]; }

    return 0;
}
EOF

# Makefile
cat << 'EOF' > Makefile
CFLAGS = -Wall -std=c11 -g
CXXFLAGS = -Wall -O2 -pipe
TARGET=target
SRCS=$(wildcard *.cpp)
OBJS=$(SRCS:.cpp=.o)

all: clean $(TARGET) test


$(TARGET): $(OBJS)
	$(CXX) -o $@ $(OBJS)

clean:
	rm -f $(TARGET) $(OBJS) 

test:
	bash ./test.sh

.PHONY: all clean $(TARGET) test
EOF

# Test script
cat << 'EOF' > test.sh
#!/bin/bash

TARGET=./target


echo "---"
${TARGET} <<EOS
EOS


echo "---"
${TARGET} <<EOS
EOS


echo "---"
${TARGET} <<EOS
EOS
EOF
