#!/bin/bash

BMFILE="${HOME}/bookmark_path.txt"
BMFILE_BAK="${BMFILE}.bak"
path=""
query=""
bmfileonly=0
interactive=0

echoB() { echo -e "$(tput bold)$1$(tput sgr0)"; }
function help() ## show help
{
    echoB "USAGE:"
    echo "$0 [-bih] [-q query] command"
    echo ""
    echoB "COMMAND:"
    grep -E '^function [a-zA-Z_-]+ *\( *\) *## .*$$' $0 | cut -d " " -f2- | sort \
        | awk ' \
             BEGIN {FS = "\\( *\\) *##"} \
             {args = ""; breif = ""} \
             match($2, /a:.+b:/) {args = substr($2, RSTART+2, RLENGTH-2-2)} \
             {printf "\033[33m%s\033[36m%s\033[0m\n\t%s\n",\
                       $1, args, substr($2, RSTART+RLENGTH), length($2)-RSTART}'
    echo ""
    echoB "OPTION:"
    echo "-b: use bookmark file only. no use ghq list."
    echo "-q: set query for search"
    echo "-i: intaractive mode"
    echo "-h: print help"
    echo ""
}

search()
{
    test ! -n "$path" && path=$(pwd)
    cat ${BMFILE} | grep -n -x ${path} | cut -d ":" -f 1
}

function add() ## add path to bookmark
{
    local linenum= $(search)
    echo "add path: $path"
    test ! -n "$linenum" && { cp $BMFILE $BMFILE_BAK; echo $path >> $BMFILE; }
}

function del() ## remove path from bookmark.
{
    test $intaractive -eq 1 && path=$(cat $BMFILE | peco)
    local linenum= $(search)
    echo "remove path: $path"
    if [ -n "$linenum" ]; then
        cp $BMFILE $BMFILE_BAK
        sed -e "${linenum}d" $BMFILE_BAK > $BMFILE
        sed -e "${linenum}d" $BMFILE_BAK
    fi
}

function show() ## show bookmark list
{
    local cmd="cat $BMFILE"
    test $bmfileonly -eq 0 && cmd=$cmd"; ghq list --full-path"

    local pecoopt=""
    test -n "$query" && pecoopt="--query $query"

    echo "$(eval $cmd)" | peco $pecoopt
}

main()
{
    while getopts "lp:q:h" flag; do
        case $flag in
            \?) OPT_ERR=1; break;;
            b) bmfileonly=1;;
            q) query="$OPTARG";;
            i) interactive=1;;
            h) help; exit 0;;
        esac
    done

    shift $(($OPTIND - 1))
    test $OPT_ERR && { help; exit 1; }

    case $1 in
        "add" | \
        "rm"  | \
        "show") $1 ${@:2};;
        "") show ;;
        * ) help; exit 1;;
    esac

    exit 0
}

main $@
